//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.17379.
// 
#pragma warning disable 1591

namespace ВебКлиентБеларусь.by.nbrb.www {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17379")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ExRatesSoap", Namespace="http://www.nbrb.by/")]
    public partial class ExRates : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CurrenciesRefDailyOperationCompleted;
        
        private System.Threading.SendOrPostCallback CurrenciesRefMonthlyOperationCompleted;
        
        private System.Threading.SendOrPostCallback StartDateOperationCompleted;
        
        private System.Threading.SendOrPostCallback LastDailyExRatesDateOperationCompleted;
        
        private System.Threading.SendOrPostCallback LastMonthlyExRatesDateOperationCompleted;
        
        private System.Threading.SendOrPostCallback ExRatesDailyOperationCompleted;
        
        private System.Threading.SendOrPostCallback ExRatesMonthlyOperationCompleted;
        
        private System.Threading.SendOrPostCallback ExRatesDynOperationCompleted;
        
        private System.Threading.SendOrPostCallback CurrenciesRefOperationCompleted;
        
        private System.Threading.SendOrPostCallback MetalsLastDateOperationCompleted;
        
        private System.Threading.SendOrPostCallback MetalsRefOperationCompleted;
        
        private System.Threading.SendOrPostCallback MetalsPricesOperationCompleted;
        
        private System.Threading.SendOrPostCallback IngotsPricesOperationCompleted;
        
        private System.Threading.SendOrPostCallback IngotsLastDateOperationCompleted;
        
        private System.Threading.SendOrPostCallback StockAddRatesOperationCompleted;
        
        private System.Threading.SendOrPostCallback StockAddRatesLastDateOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ExRates() {
            this.Url = global::ВебКлиентБеларусь.Properties.Settings.Default.ВебКлиентБеларусь_by_nbrb_www_ExRates;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CurrenciesRefDailyCompletedEventHandler CurrenciesRefDailyCompleted;
        
        /// <remarks/>
        public event CurrenciesRefMonthlyCompletedEventHandler CurrenciesRefMonthlyCompleted;
        
        /// <remarks/>
        public event StartDateCompletedEventHandler StartDateCompleted;
        
        /// <remarks/>
        public event LastDailyExRatesDateCompletedEventHandler LastDailyExRatesDateCompleted;
        
        /// <remarks/>
        public event LastMonthlyExRatesDateCompletedEventHandler LastMonthlyExRatesDateCompleted;
        
        /// <remarks/>
        public event ExRatesDailyCompletedEventHandler ExRatesDailyCompleted;
        
        /// <remarks/>
        public event ExRatesMonthlyCompletedEventHandler ExRatesMonthlyCompleted;
        
        /// <remarks/>
        public event ExRatesDynCompletedEventHandler ExRatesDynCompleted;
        
        /// <remarks/>
        public event CurrenciesRefCompletedEventHandler CurrenciesRefCompleted;
        
        /// <remarks/>
        public event MetalsLastDateCompletedEventHandler MetalsLastDateCompleted;
        
        /// <remarks/>
        public event MetalsRefCompletedEventHandler MetalsRefCompleted;
        
        /// <remarks/>
        public event MetalsPricesCompletedEventHandler MetalsPricesCompleted;
        
        /// <remarks/>
        public event IngotsPricesCompletedEventHandler IngotsPricesCompleted;
        
        /// <remarks/>
        public event IngotsLastDateCompletedEventHandler IngotsLastDateCompleted;
        
        /// <remarks/>
        public event StockAddRatesCompletedEventHandler StockAddRatesCompleted;
        
        /// <remarks/>
        public event StockAddRatesLastDateCompletedEventHandler StockAddRatesLastDateCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.nbrb.by/CurrenciesRefDaily", RequestNamespace="http://www.nbrb.by/", ResponseNamespace="http://www.nbrb.by/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet CurrenciesRefDaily() {
            object[] results = this.Invoke("CurrenciesRefDaily", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void CurrenciesRefDailyAsync() {
            this.CurrenciesRefDailyAsync(null);
        }
        
        /// <remarks/>
        public void CurrenciesRefDailyAsync(object userState) {
            if ((this.CurrenciesRefDailyOperationCompleted == null)) {
                this.CurrenciesRefDailyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCurrenciesRefDailyOperationCompleted);
            }
            this.InvokeAsync("CurrenciesRefDaily", new object[0], this.CurrenciesRefDailyOperationCompleted, userState);
        }
        
        private void OnCurrenciesRefDailyOperationCompleted(object arg) {
            if ((this.CurrenciesRefDailyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CurrenciesRefDailyCompleted(this, new CurrenciesRefDailyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.nbrb.by/CurrenciesRefMonthly", RequestNamespace="http://www.nbrb.by/", ResponseNamespace="http://www.nbrb.by/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet CurrenciesRefMonthly() {
            object[] results = this.Invoke("CurrenciesRefMonthly", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void CurrenciesRefMonthlyAsync() {
            this.CurrenciesRefMonthlyAsync(null);
        }
        
        /// <remarks/>
        public void CurrenciesRefMonthlyAsync(object userState) {
            if ((this.CurrenciesRefMonthlyOperationCompleted == null)) {
                this.CurrenciesRefMonthlyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCurrenciesRefMonthlyOperationCompleted);
            }
            this.InvokeAsync("CurrenciesRefMonthly", new object[0], this.CurrenciesRefMonthlyOperationCompleted, userState);
        }
        
        private void OnCurrenciesRefMonthlyOperationCompleted(object arg) {
            if ((this.CurrenciesRefMonthlyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CurrenciesRefMonthlyCompleted(this, new CurrenciesRefMonthlyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.nbrb.by/StartDate", RequestNamespace="http://www.nbrb.by/", ResponseNamespace="http://www.nbrb.by/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.DateTime StartDate(int Periodicity) {
            object[] results = this.Invoke("StartDate", new object[] {
                        Periodicity});
            return ((System.DateTime)(results[0]));
        }
        
        /// <remarks/>
        public void StartDateAsync(int Periodicity) {
            this.StartDateAsync(Periodicity, null);
        }
        
        /// <remarks/>
        public void StartDateAsync(int Periodicity, object userState) {
            if ((this.StartDateOperationCompleted == null)) {
                this.StartDateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStartDateOperationCompleted);
            }
            this.InvokeAsync("StartDate", new object[] {
                        Periodicity}, this.StartDateOperationCompleted, userState);
        }
        
        private void OnStartDateOperationCompleted(object arg) {
            if ((this.StartDateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StartDateCompleted(this, new StartDateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.nbrb.by/LastDailyExRatesDate", RequestNamespace="http://www.nbrb.by/", ResponseNamespace="http://www.nbrb.by/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.DateTime LastDailyExRatesDate() {
            object[] results = this.Invoke("LastDailyExRatesDate", new object[0]);
            return ((System.DateTime)(results[0]));
        }
        
        /// <remarks/>
        public void LastDailyExRatesDateAsync() {
            this.LastDailyExRatesDateAsync(null);
        }
        
        /// <remarks/>
        public void LastDailyExRatesDateAsync(object userState) {
            if ((this.LastDailyExRatesDateOperationCompleted == null)) {
                this.LastDailyExRatesDateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLastDailyExRatesDateOperationCompleted);
            }
            this.InvokeAsync("LastDailyExRatesDate", new object[0], this.LastDailyExRatesDateOperationCompleted, userState);
        }
        
        private void OnLastDailyExRatesDateOperationCompleted(object arg) {
            if ((this.LastDailyExRatesDateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LastDailyExRatesDateCompleted(this, new LastDailyExRatesDateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.nbrb.by/LastMonthlyExRatesDate", RequestNamespace="http://www.nbrb.by/", ResponseNamespace="http://www.nbrb.by/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.DateTime LastMonthlyExRatesDate() {
            object[] results = this.Invoke("LastMonthlyExRatesDate", new object[0]);
            return ((System.DateTime)(results[0]));
        }
        
        /// <remarks/>
        public void LastMonthlyExRatesDateAsync() {
            this.LastMonthlyExRatesDateAsync(null);
        }
        
        /// <remarks/>
        public void LastMonthlyExRatesDateAsync(object userState) {
            if ((this.LastMonthlyExRatesDateOperationCompleted == null)) {
                this.LastMonthlyExRatesDateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLastMonthlyExRatesDateOperationCompleted);
            }
            this.InvokeAsync("LastMonthlyExRatesDate", new object[0], this.LastMonthlyExRatesDateOperationCompleted, userState);
        }
        
        private void OnLastMonthlyExRatesDateOperationCompleted(object arg) {
            if ((this.LastMonthlyExRatesDateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LastMonthlyExRatesDateCompleted(this, new LastMonthlyExRatesDateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.nbrb.by/ExRatesDaily", RequestNamespace="http://www.nbrb.by/", ResponseNamespace="http://www.nbrb.by/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ExRatesDaily(System.DateTime onDate) {
            object[] results = this.Invoke("ExRatesDaily", new object[] {
                        onDate});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ExRatesDailyAsync(System.DateTime onDate) {
            this.ExRatesDailyAsync(onDate, null);
        }
        
        /// <remarks/>
        public void ExRatesDailyAsync(System.DateTime onDate, object userState) {
            if ((this.ExRatesDailyOperationCompleted == null)) {
                this.ExRatesDailyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExRatesDailyOperationCompleted);
            }
            this.InvokeAsync("ExRatesDaily", new object[] {
                        onDate}, this.ExRatesDailyOperationCompleted, userState);
        }
        
        private void OnExRatesDailyOperationCompleted(object arg) {
            if ((this.ExRatesDailyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExRatesDailyCompleted(this, new ExRatesDailyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.nbrb.by/ExRatesMonthly", RequestNamespace="http://www.nbrb.by/", ResponseNamespace="http://www.nbrb.by/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ExRatesMonthly(System.DateTime onDate) {
            object[] results = this.Invoke("ExRatesMonthly", new object[] {
                        onDate});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ExRatesMonthlyAsync(System.DateTime onDate) {
            this.ExRatesMonthlyAsync(onDate, null);
        }
        
        /// <remarks/>
        public void ExRatesMonthlyAsync(System.DateTime onDate, object userState) {
            if ((this.ExRatesMonthlyOperationCompleted == null)) {
                this.ExRatesMonthlyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExRatesMonthlyOperationCompleted);
            }
            this.InvokeAsync("ExRatesMonthly", new object[] {
                        onDate}, this.ExRatesMonthlyOperationCompleted, userState);
        }
        
        private void OnExRatesMonthlyOperationCompleted(object arg) {
            if ((this.ExRatesMonthlyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExRatesMonthlyCompleted(this, new ExRatesMonthlyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.nbrb.by/ExRatesDyn", RequestNamespace="http://www.nbrb.by/", ResponseNamespace="http://www.nbrb.by/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ExRatesDyn(int curId, System.DateTime fromDate, System.DateTime toDate) {
            object[] results = this.Invoke("ExRatesDyn", new object[] {
                        curId,
                        fromDate,
                        toDate});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ExRatesDynAsync(int curId, System.DateTime fromDate, System.DateTime toDate) {
            this.ExRatesDynAsync(curId, fromDate, toDate, null);
        }
        
        /// <remarks/>
        public void ExRatesDynAsync(int curId, System.DateTime fromDate, System.DateTime toDate, object userState) {
            if ((this.ExRatesDynOperationCompleted == null)) {
                this.ExRatesDynOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExRatesDynOperationCompleted);
            }
            this.InvokeAsync("ExRatesDyn", new object[] {
                        curId,
                        fromDate,
                        toDate}, this.ExRatesDynOperationCompleted, userState);
        }
        
        private void OnExRatesDynOperationCompleted(object arg) {
            if ((this.ExRatesDynCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExRatesDynCompleted(this, new ExRatesDynCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.nbrb.by/CurrenciesRef", RequestNamespace="http://www.nbrb.by/", ResponseNamespace="http://www.nbrb.by/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet CurrenciesRef(int Periodicity) {
            object[] results = this.Invoke("CurrenciesRef", new object[] {
                        Periodicity});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void CurrenciesRefAsync(int Periodicity) {
            this.CurrenciesRefAsync(Periodicity, null);
        }
        
        /// <remarks/>
        public void CurrenciesRefAsync(int Periodicity, object userState) {
            if ((this.CurrenciesRefOperationCompleted == null)) {
                this.CurrenciesRefOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCurrenciesRefOperationCompleted);
            }
            this.InvokeAsync("CurrenciesRef", new object[] {
                        Periodicity}, this.CurrenciesRefOperationCompleted, userState);
        }
        
        private void OnCurrenciesRefOperationCompleted(object arg) {
            if ((this.CurrenciesRefCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CurrenciesRefCompleted(this, new CurrenciesRefCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.nbrb.by/MetalsLastDate", RequestNamespace="http://www.nbrb.by/", ResponseNamespace="http://www.nbrb.by/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.DateTime MetalsLastDate() {
            object[] results = this.Invoke("MetalsLastDate", new object[0]);
            return ((System.DateTime)(results[0]));
        }
        
        /// <remarks/>
        public void MetalsLastDateAsync() {
            this.MetalsLastDateAsync(null);
        }
        
        /// <remarks/>
        public void MetalsLastDateAsync(object userState) {
            if ((this.MetalsLastDateOperationCompleted == null)) {
                this.MetalsLastDateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMetalsLastDateOperationCompleted);
            }
            this.InvokeAsync("MetalsLastDate", new object[0], this.MetalsLastDateOperationCompleted, userState);
        }
        
        private void OnMetalsLastDateOperationCompleted(object arg) {
            if ((this.MetalsLastDateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MetalsLastDateCompleted(this, new MetalsLastDateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.nbrb.by/MetalsRef", RequestNamespace="http://www.nbrb.by/", ResponseNamespace="http://www.nbrb.by/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet MetalsRef() {
            object[] results = this.Invoke("MetalsRef", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void MetalsRefAsync() {
            this.MetalsRefAsync(null);
        }
        
        /// <remarks/>
        public void MetalsRefAsync(object userState) {
            if ((this.MetalsRefOperationCompleted == null)) {
                this.MetalsRefOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMetalsRefOperationCompleted);
            }
            this.InvokeAsync("MetalsRef", new object[0], this.MetalsRefOperationCompleted, userState);
        }
        
        private void OnMetalsRefOperationCompleted(object arg) {
            if ((this.MetalsRefCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MetalsRefCompleted(this, new MetalsRefCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.nbrb.by/MetalsPrices", RequestNamespace="http://www.nbrb.by/", ResponseNamespace="http://www.nbrb.by/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet MetalsPrices(int MetalId, System.DateTime fromDate, System.DateTime toDate) {
            object[] results = this.Invoke("MetalsPrices", new object[] {
                        MetalId,
                        fromDate,
                        toDate});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void MetalsPricesAsync(int MetalId, System.DateTime fromDate, System.DateTime toDate) {
            this.MetalsPricesAsync(MetalId, fromDate, toDate, null);
        }
        
        /// <remarks/>
        public void MetalsPricesAsync(int MetalId, System.DateTime fromDate, System.DateTime toDate, object userState) {
            if ((this.MetalsPricesOperationCompleted == null)) {
                this.MetalsPricesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMetalsPricesOperationCompleted);
            }
            this.InvokeAsync("MetalsPrices", new object[] {
                        MetalId,
                        fromDate,
                        toDate}, this.MetalsPricesOperationCompleted, userState);
        }
        
        private void OnMetalsPricesOperationCompleted(object arg) {
            if ((this.MetalsPricesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MetalsPricesCompleted(this, new MetalsPricesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.nbrb.by/IngotsPrices", RequestNamespace="http://www.nbrb.by/", ResponseNamespace="http://www.nbrb.by/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet IngotsPrices(System.DateTime onDate) {
            object[] results = this.Invoke("IngotsPrices", new object[] {
                        onDate});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void IngotsPricesAsync(System.DateTime onDate) {
            this.IngotsPricesAsync(onDate, null);
        }
        
        /// <remarks/>
        public void IngotsPricesAsync(System.DateTime onDate, object userState) {
            if ((this.IngotsPricesOperationCompleted == null)) {
                this.IngotsPricesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIngotsPricesOperationCompleted);
            }
            this.InvokeAsync("IngotsPrices", new object[] {
                        onDate}, this.IngotsPricesOperationCompleted, userState);
        }
        
        private void OnIngotsPricesOperationCompleted(object arg) {
            if ((this.IngotsPricesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IngotsPricesCompleted(this, new IngotsPricesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.nbrb.by/IngotsLastDate", RequestNamespace="http://www.nbrb.by/", ResponseNamespace="http://www.nbrb.by/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.DateTime IngotsLastDate() {
            object[] results = this.Invoke("IngotsLastDate", new object[0]);
            return ((System.DateTime)(results[0]));
        }
        
        /// <remarks/>
        public void IngotsLastDateAsync() {
            this.IngotsLastDateAsync(null);
        }
        
        /// <remarks/>
        public void IngotsLastDateAsync(object userState) {
            if ((this.IngotsLastDateOperationCompleted == null)) {
                this.IngotsLastDateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIngotsLastDateOperationCompleted);
            }
            this.InvokeAsync("IngotsLastDate", new object[0], this.IngotsLastDateOperationCompleted, userState);
        }
        
        private void OnIngotsLastDateOperationCompleted(object arg) {
            if ((this.IngotsLastDateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IngotsLastDateCompleted(this, new IngotsLastDateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.nbrb.by/StockAddRates", RequestNamespace="http://www.nbrb.by/", ResponseNamespace="http://www.nbrb.by/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet StockAddRates(System.DateTime onDate) {
            object[] results = this.Invoke("StockAddRates", new object[] {
                        onDate});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void StockAddRatesAsync(System.DateTime onDate) {
            this.StockAddRatesAsync(onDate, null);
        }
        
        /// <remarks/>
        public void StockAddRatesAsync(System.DateTime onDate, object userState) {
            if ((this.StockAddRatesOperationCompleted == null)) {
                this.StockAddRatesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStockAddRatesOperationCompleted);
            }
            this.InvokeAsync("StockAddRates", new object[] {
                        onDate}, this.StockAddRatesOperationCompleted, userState);
        }
        
        private void OnStockAddRatesOperationCompleted(object arg) {
            if ((this.StockAddRatesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StockAddRatesCompleted(this, new StockAddRatesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.nbrb.by/StockAddRatesLastDate", RequestNamespace="http://www.nbrb.by/", ResponseNamespace="http://www.nbrb.by/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.DateTime StockAddRatesLastDate() {
            object[] results = this.Invoke("StockAddRatesLastDate", new object[0]);
            return ((System.DateTime)(results[0]));
        }
        
        /// <remarks/>
        public void StockAddRatesLastDateAsync() {
            this.StockAddRatesLastDateAsync(null);
        }
        
        /// <remarks/>
        public void StockAddRatesLastDateAsync(object userState) {
            if ((this.StockAddRatesLastDateOperationCompleted == null)) {
                this.StockAddRatesLastDateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStockAddRatesLastDateOperationCompleted);
            }
            this.InvokeAsync("StockAddRatesLastDate", new object[0], this.StockAddRatesLastDateOperationCompleted, userState);
        }
        
        private void OnStockAddRatesLastDateOperationCompleted(object arg) {
            if ((this.StockAddRatesLastDateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StockAddRatesLastDateCompleted(this, new StockAddRatesLastDateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17379")]
    public delegate void CurrenciesRefDailyCompletedEventHandler(object sender, CurrenciesRefDailyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17379")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CurrenciesRefDailyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CurrenciesRefDailyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17379")]
    public delegate void CurrenciesRefMonthlyCompletedEventHandler(object sender, CurrenciesRefMonthlyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17379")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CurrenciesRefMonthlyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CurrenciesRefMonthlyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17379")]
    public delegate void StartDateCompletedEventHandler(object sender, StartDateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17379")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StartDateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal StartDateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.DateTime Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.DateTime)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17379")]
    public delegate void LastDailyExRatesDateCompletedEventHandler(object sender, LastDailyExRatesDateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17379")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LastDailyExRatesDateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LastDailyExRatesDateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.DateTime Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.DateTime)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17379")]
    public delegate void LastMonthlyExRatesDateCompletedEventHandler(object sender, LastMonthlyExRatesDateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17379")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LastMonthlyExRatesDateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LastMonthlyExRatesDateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.DateTime Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.DateTime)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17379")]
    public delegate void ExRatesDailyCompletedEventHandler(object sender, ExRatesDailyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17379")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExRatesDailyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ExRatesDailyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17379")]
    public delegate void ExRatesMonthlyCompletedEventHandler(object sender, ExRatesMonthlyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17379")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExRatesMonthlyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ExRatesMonthlyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17379")]
    public delegate void ExRatesDynCompletedEventHandler(object sender, ExRatesDynCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17379")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExRatesDynCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ExRatesDynCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17379")]
    public delegate void CurrenciesRefCompletedEventHandler(object sender, CurrenciesRefCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17379")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CurrenciesRefCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CurrenciesRefCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17379")]
    public delegate void MetalsLastDateCompletedEventHandler(object sender, MetalsLastDateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17379")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MetalsLastDateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MetalsLastDateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.DateTime Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.DateTime)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17379")]
    public delegate void MetalsRefCompletedEventHandler(object sender, MetalsRefCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17379")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MetalsRefCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MetalsRefCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17379")]
    public delegate void MetalsPricesCompletedEventHandler(object sender, MetalsPricesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17379")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MetalsPricesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MetalsPricesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17379")]
    public delegate void IngotsPricesCompletedEventHandler(object sender, IngotsPricesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17379")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IngotsPricesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IngotsPricesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17379")]
    public delegate void IngotsLastDateCompletedEventHandler(object sender, IngotsLastDateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17379")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IngotsLastDateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IngotsLastDateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.DateTime Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.DateTime)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17379")]
    public delegate void StockAddRatesCompletedEventHandler(object sender, StockAddRatesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17379")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StockAddRatesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal StockAddRatesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17379")]
    public delegate void StockAddRatesLastDateCompletedEventHandler(object sender, StockAddRatesLastDateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17379")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StockAddRatesLastDateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal StockAddRatesLastDateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.DateTime Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.DateTime)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591