//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.17379.
// 
#pragma warning disable 1591

namespace ВебКлиентMorpher.ru.morpher.www {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17379")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MorpherSoap", Namespace="http://morpher.ru/webservices/")]
    public partial class Morpher : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback PropisRUBOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFormsOperationCompleted;
        
        private System.Threading.SendOrPostCallback SoglasovatOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Morpher() {
            this.Url = global::ВебКлиентMorpher.Properties.Settings.Default.ВебКлиентMorpher_ru_morpher_www_Morpher;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event PropisRUBCompletedEventHandler PropisRUBCompleted;
        
        /// <remarks/>
        public event GetFormsCompletedEventHandler GetFormsCompleted;
        
        /// <remarks/>
        public event SoglasovatCompletedEventHandler SoglasovatCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://morpher.ru/webservices/PropisRUB", RequestNamespace="http://morpher.ru/webservices/", ResponseNamespace="http://morpher.ru/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string PropisRUB(decimal summa) {
            object[] results = this.Invoke("PropisRUB", new object[] {
                        summa});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PropisRUBAsync(decimal summa) {
            this.PropisRUBAsync(summa, null);
        }
        
        /// <remarks/>
        public void PropisRUBAsync(decimal summa, object userState) {
            if ((this.PropisRUBOperationCompleted == null)) {
                this.PropisRUBOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPropisRUBOperationCompleted);
            }
            this.InvokeAsync("PropisRUB", new object[] {
                        summa}, this.PropisRUBOperationCompleted, userState);
        }
        
        private void OnPropisRUBOperationCompleted(object arg) {
            if ((this.PropisRUBCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PropisRUBCompleted(this, new PropisRUBCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://morpher.ru/webservices/GetForms", RequestNamespace="http://morpher.ru/webservices/", ResponseNamespace="http://morpher.ru/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetForms(string s) {
            object[] results = this.Invoke("GetForms", new object[] {
                        s});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetFormsAsync(string s) {
            this.GetFormsAsync(s, null);
        }
        
        /// <remarks/>
        public void GetFormsAsync(string s, object userState) {
            if ((this.GetFormsOperationCompleted == null)) {
                this.GetFormsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFormsOperationCompleted);
            }
            this.InvokeAsync("GetForms", new object[] {
                        s}, this.GetFormsOperationCompleted, userState);
        }
        
        private void OnGetFormsOperationCompleted(object arg) {
            if ((this.GetFormsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFormsCompleted(this, new GetFormsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://morpher.ru/webservices/Soglasovat", RequestNamespace="http://morpher.ru/webservices/", ResponseNamespace="http://morpher.ru/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Soglasovat(uint n, string s) {
            object[] results = this.Invoke("Soglasovat", new object[] {
                        n,
                        s});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SoglasovatAsync(uint n, string s) {
            this.SoglasovatAsync(n, s, null);
        }
        
        /// <remarks/>
        public void SoglasovatAsync(uint n, string s, object userState) {
            if ((this.SoglasovatOperationCompleted == null)) {
                this.SoglasovatOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSoglasovatOperationCompleted);
            }
            this.InvokeAsync("Soglasovat", new object[] {
                        n,
                        s}, this.SoglasovatOperationCompleted, userState);
        }
        
        private void OnSoglasovatOperationCompleted(object arg) {
            if ((this.SoglasovatCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SoglasovatCompleted(this, new SoglasovatCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17379")]
    public delegate void PropisRUBCompletedEventHandler(object sender, PropisRUBCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17379")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PropisRUBCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PropisRUBCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17379")]
    public delegate void GetFormsCompletedEventHandler(object sender, GetFormsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17379")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFormsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFormsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17379")]
    public delegate void SoglasovatCompletedEventHandler(object sender, SoglasovatCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17379")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SoglasovatCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SoglasovatCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591