//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _006_Update
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers
    {
        public int Id { get; set; }
        public string Nme { get; set; }
        public string SName { get; set; }
    }
}
