//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _002_OneToMany
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public Car()
        {
            this.Models = new HashSet<Model>();
        }
    
        public int Id { get; set; }
        public string Factory { get; set; }
        public string Country { get; set; }
    
        public virtual ICollection<Model> Models { get; set; }
    }
}
