//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _001_OneToOne
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeInf
    {
        public int Id { get; set; }
        public string Age { get; set; }
        public string Gender { get; set; }
        public string Phone { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
